---
title: "Qu'est-ce que c'est Ant Hunters?"
title-block-banner: false
comments: false
---

Ce projet de science citoyenne est dirigé par des [chercheurs](team.qmd) du Groupe d'Écologie des Fourmis de la Station Biologique de Doñana (EBD - CSIC), vous invitant à devenir chercheur et à explorer la biodiversité de ces incroyables insectes dans votre environnement.

Nous **vous enseignons** l'une des méthodes d'échantillonnage utilisées par les chercheurs pour étudier les fourmis. Nous vous proposons deux façons de participer : l'une en tant que citoyen scientifique et l'autre en tant qu'enseignant. Vous pourrez apprendre et tirer vos propres conclusions, et **si vous êtes enseignant**, vous pourrez l'utiliser comme activité avec vos élèves. **Comment?** C'est simple et amusant! Vous placerez des appâts d'eau sucrée et observerez les espèces qui coexistent avec vous et comment elles vivent ensemble. Nous vous fournirons un **kit AntHunter** complet avec tout le nécessaire, y compris des instructions détaillées et du matériel pour la collecte d'échantillons. En plus, nous vous suggérerons des activités complémentaires que vous pourrez réaliser après l'étude en utilisant le matériel du kit.

Ce projet vous permettra non seulement d'en apprendre davantage sur la biologie et le comportement des fourmis, mais aussi de devenir un acteur actif dans la production de connaissances scientifiques. Votre participation aidera les scientifiques à collecter des échantillons et à mieux comprendre les aspects clés de la distribution, des interactions, de la microbiologie et de la génétique des fourmis. Vous n'avez pas besoin d'être un expert, juste curieux et désireux de contribuer à la science.

Devenez un Chasseur de Fourmis et faites partie de ce projet passionnant!
