---
title: "O que é Ant Hunters?"
title-block-banner: false
comments: false
---

Este é um projeto de ciência cidadã coordenado por [investigadores](team.qmd) do Grupo de Ecologia de Formigas da Estação Biológica de Doñana (EBD - CSIC), convidando-o a tornar-se um investigador e explorar a biodiversidade destes incríveis insetos no seu ambiente.

Nós **ensinamos-lhe** um dos métodos de amostragem que os investigadores utilizam para estudar formigas. Oferecemos-lhe duas formas de participar: uma como cientista cidadão e outra como professor. Poderá aprender e tirar as suas próprias conclusões e, **se for professor**, poderá utilizá-lo como uma atividade com os seus alunos. **Como?** É simples e divertido! Irá colocar iscos de água com açúcar e observar as espécies que coexistem consigo e como vêm viver juntas. Forneceremos um **kit AntHunter** completo com tudo o que precisa, incluindo instruções detalhadas e materiais para a recolha de amostras. Além disso, sugeriremos atividades complementares que poderá realizar após o estudo utilizando os materiais do kit.

Este projeto não só lhe permitirá aprender sobre a biologia e o comportamento das formigas, como também o tornará um participante ativo na geração de conhecimento científico. A sua participação ajudará os cientistas a recolher amostras e a compreender melhor aspetos chave da distribuição, interações, microbiologia e genética das formigas. Não precisa de ser um especialista, apenas curioso e disposto a contribuir para a ciência.

Torne-se um Ant Hunter e faça parte deste projeto emocionante!
