---
title: "Was ist Ant Hunters?"
title-block-banner: false
comments: false
---

Dies ist ein Bürgerwissenschaftsprojekt, koordiniert von [Forschern](team.qmd) der Ameisenökologie-Gruppe an der Biologischen Station Doñana (EBD - CSIC), das Sie einlädt, selbst zum Forscher zu werden und die Artenvielfalt dieser faszinierenden Insekten in Ihrer Umgebung zu erkunden.

**Wir zeigen Ihnen** eine der Probenahmemethoden, die Forscher zur Untersuchung von Ameisen verwenden. Wir bieten Ihnen zwei Möglichkeiten zur Teilnahme: eine als Bürgerwissenschaftler und eine weitere als Lehrer. Sie werden in der Lage sein zu lernen und Ihre eigenen Schlussfolgerungen zu ziehen, und **wenn Sie Lehrer sind**, können Sie es als Aktivität mit Ihren Schülern nutzen. **Wie?** Es ist einfach und macht Spaß! Sie werden Zuckerwasser-Ködern platzieren und die Arten beobachten, die mit Ihnen zusammenleben und wie sie zusammenleben. Wir stellen Ihnen ein komplettes **AntHunter-Kit** mit allem Notwendigen zur Verfügung, einschließlich detaillierter Anweisungen und Materialien für die Probenentnahme. Zusätzlich schlagen wir Ihnen ergänzende Aktivitäten vor, die Sie nach der Studie mit den Materialien des Kits durchführen können.

Dieses Projekt ermöglicht es Ihnen nicht nur, etwas über die Biologie und das Verhalten von Ameisen zu lernen, sondern macht Sie auch zu einem aktiven Teilnehmer an der Generierung wissenschaftlichen Wissens. Ihre Teilnahme wird Wissenschaftlern helfen, Proben zu sammeln und wichtige Aspekte der Ameisenverbreitung, Interaktionen, Mikrobiologie und Genetik besser zu verstehen. Sie müssen kein Experte sein, nur neugierig und bereit, zur Wissenschaft beizutragen.

Werden Sie ein Ameisenjäger und seien Sie Teil dieses aufregenden Projekts!
